import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../constants/HomeConstants';

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.grayBg },
  scroll: { flex: 1 },
  content: { paddingBottom: 32 },
  header: {
    backgroundColor: COLORS.red,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoRow: { flexDirection: 'row', alignItems: 'center' },
  logo: { width: 88, height: 28 },
  headerIcons: { flexDirection: 'row', gap: 14 },
  greet: { color: COLORS.white, fontSize: 20, fontWeight: '700', marginTop: 12 },
  pypBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pypBannerRestricted: {
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: '#FECACA',
  },
  pypBannerFree: {
    backgroundColor: 'rgba(22,163,74,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(22,163,74,0.3)',
  },
  pypBannerText: { flex: 1 },
  pypBannerTitle: {
    fontWeight: '700',
    fontSize: 14,
  },
  pypBannerTitleRestricted: { color: '#DC2626' },
  pypBannerTitleFree: { color: '#BBF7D0' },
  pypBannerSub: {
    color: COLORS.white,
    fontSize: 12,
    marginTop: 2,
    opacity: 0.85,
  },
  pypBannerSubRestricted: {
    color: COLORS.mid,
    opacity: 1,
  },
  openOtpBtn: {
    alignSelf: 'flex-start',
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.white,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  openOtpText: { color: COLORS.white, fontWeight: '600' },
  spinnerRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 12,
    marginTop: 12,
  },
  card: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cardTitle: { color: COLORS.mid, fontSize: 13 },
  cardValue: { fontSize: 22, fontWeight: '700', marginTop: 8 },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
  },
  cardLink: { color: COLORS.mid, fontSize: 12 },
  prefCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginHorizontal: 12,
    marginTop: 16,
    padding: 12,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  prefImage: { width: 80, height: 80, borderRadius: 12 },
  prefTextCol: { flex: 1, justifyContent: 'center' },
  prefText: { color: COLORS.dark, fontSize: 14, lineHeight: 20 },
  prefBtn: {
    borderWidth: 1,
    borderColor: COLORS.mid,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  prefBtnText: { color: COLORS.dark, fontWeight: '600' },
  sectionTitle: {
    color: COLORS.dark,
    fontSize: 18,
    fontWeight: '700',
    paddingHorizontal: 16,
    marginTop: 16,
  },
  gridRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 16,
  },
  gridItem: {
    alignItems: 'center',
    width: 72,
  },
  gridIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridIconGreen: { backgroundColor: '#E8FFF3' },
  gridIconBlue: { backgroundColor: '#E6F2FF' },
  gridIconOrange: { backgroundColor: '#FFF5E6' },
  gridIconFuchsia: { backgroundColor: '#FCE4F2' },
  gridLabel: { marginTop: 6, color: COLORS.dark, fontSize: 12 },
  carouselBlock: { marginTop: 12, alignItems: 'center' },
  banner: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  bannerHeader: { paddingHorizontal: 12, paddingTop: 12 },
  bannerTitle: { color: COLORS.blue, fontWeight: '700' },
  bannerImage: { width: '100%', height: 140 },
  bannerCta: {
    backgroundColor: COLORS.red,
    borderRadius: 8,
    alignSelf: 'flex-start',
    margin: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bannerCtaText: { color: COLORS.white, fontWeight: '700' },
  dotsRow: { flexDirection: 'row', gap: 6, marginTop: 8 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#CBD5E1' },
  dotActive: { backgroundColor: COLORS.red },
  pointsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 20,
  },
  viewAll: { color: COLORS.blue, fontWeight: '600' },
  pointsCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: 12,
    width: Dimensions.get('window').width - 24,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  pointsImg: { width: '100%', height: 120 },
  pointsText: {
    color: COLORS.dark,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pointsCoin: {
    position: 'absolute',
    top: 8,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 14,
    padding: 6,
  },
  quickBtn: {
    position: 'absolute',
    bottom: -16,
    right: 24,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickBtnText: { color: COLORS.white, fontWeight: '700' },
  bottomTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 10,
    marginTop: 32,
  },
  tabItem: { alignItems: 'center' },
  tabItemActive: { alignItems: 'center' },
  tabLabel: { fontSize: 11, color: COLORS.mid, marginTop: 4 },
  tabLabelActive: {
    fontSize: 11,
    color: COLORS.red,
    fontWeight: '700',
    marginTop: 4,
  },
  tabCenter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
